apiVersion: v1 
kind: Pod
metadata:
  name: myapp-pod 
  labels:
    app: myapp
    type: front-end 
spec:
  containers:
  - name: nginx-container
    image: nginx
  affinity:  
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
        -  matchExpressions:
           -  key: size
              operator: NotIn
              values:
              - Small

      