apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: Nodeport
  ports: 
    -  targetPort: 80
       port: 80
       nodePort: 30008
  selector:
    app: myapp
    type: frontend