apiVersion: apps/v1
kind: DeamonSet
metadata:
  name: monitoring-daemon
spec:
  template:
    metadata:
    name: myapp-pod
    labels:
      app: monitroing-agent
      type: front-end
    spec:
    containers:
      - name: monitroing-agent
        image: monitroing-agent

